schemas:
    resource: @KnpJsonSchemaBundle/Resources/config/routing.yml

backend:
    type: rest
    resource: @BackendBundle/Resources/config/routing.yml
    prefix: /api/v1

frontend:
    resource: @FrontendBundle/Resources/config/routing.yml


