security:
    encoders:
        GalleryBundle\Entity\User:
            algorithm: bcrypt

        Symfony\Component\Security\Core\User\User: plaintext


    providers:
        chain_provider:
            chain:
                providers: [in_memory, gallery_users]

        # Remove this before deploy
        in_memory:
            memory:
                users:
                    admin:
                        password: qwertz
                        roles: [ 'ROLE_ADMIN', 'ROLE_USER' ]

        gallery_users:
            entity:
                class: GalleryBundle:User
                property: username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
            logout:       true
            anonymous:    true
            switch_user:  true

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

