security:
    #acl:
    #    connection: default

    encoders:
        BackendBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        chain_provider:
            chain:
                providers: [in_memory, gallery_users]

        # Remove this before deploy
        in_memory:
            memory:
                users:
                    admin:
                        password: qwertz
                        roles: [ 'ROLE_ADMIN' ]

        gallery_users:
            entity:
                class: BackendBundle:User
                property: username

    firewalls:


        main:
            pattern: ^/

            http_basic:
                provider: chain_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
            anonymous:    ~
            switch_user:  true

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY] }


