security:
    encoders:
        GalleryBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        chain_provider:
            chain:
                providers: [in_memory, gallery_users]

        # Remove this before deploy
        in_memory:
            memory:
                users:
                    admin:
                        password: qwertz
                        roles: [ 'ROLE_ADMIN' ]

        gallery_users:
            entity:
                class: GalleryBundle:User
                property: username

    firewalls:
        main:
            pattern: ^/
            http_basic:
                provider: chain_provider
            logout:       true
            anonymous:    true
            switch_user:  true

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

