login:
    path: /login
    defaults:
        _controller: FrontendBundle:Frontend:login

login_check:
    path: /login_check
    defaults:
        _controller: FrontendBundle:Frontend:loginCheck

catch_all:
    path:     /{path}
    defaults:
        _controller: FrontendBundle:Frontend:index
    requirements:
        path: "(?!js|css|bundles|_profiler).*"